# Limpieza de datos

In [14]:
import pandas as pd
df = pd.read_excel("C:/Users/anhel/OneDrive/Desktop/UNIR/Bases de datos para el Big Data/Actividad 3/visa01_grupal/act-grupal-openDataLocalesMadrid.xlsx")
print(df.shape) 

(2999, 44)


In [15]:
#Eliminar espacios en blanco a la derecha e izquierda 
#en las columnas de tipo object o cadenas de caracteres

df[df_str.columns] = df_str.apply(lambda x: x.str.strip())

In [16]:
# Eliminar columnas con datos fantasma
df.drop(['Unnamed: 36', 'Unnamed: 37', 
         'Unnamed: 38','Unnamed: 39','Unnamed: 40','Unnamed: 41',
         'Unnamed: 42','Unnamed: 43'], axis=1, inplace=True)

In [17]:
len(df["desc_distrito_local"][1])

9

In [18]:
df['hora_ini_VS_es'].unique()

array([datetime.time(8, 0), datetime.time(10, 0), datetime.time(13, 0),
       datetime.time(2, 30), datetime.time(8, 30), datetime.time(12, 0),
       datetime.time(9, 0), datetime.time(1, 30), datetime.time(0, 0),
       datetime.time(10, 24), datetime.time(11, 0)], dtype=object)

In [19]:
df['hora_fin_VS_es'].unique()

array([datetime.time(1, 30), datetime.time(2, 30), datetime.time(0, 0),
       datetime.time(1, 0), datetime.time(0, 30), datetime.time(2, 0),
       datetime.time(22, 0), datetime.time(23, 0), datetime.time(21, 0),
       datetime.time(23, 30), datetime.time(12, 0), datetime.time(8, 30),
       datetime.time(20, 30)], dtype=object)

In [20]:
df['hora_ini_VS_ra'].unique()

array([nan, datetime.time(10, 0), datetime.time(8, 0),
       datetime.time(9, 0), datetime.time(21, 0), datetime.time(2, 30),
       datetime.time(0, 0), datetime.time(11, 0), datetime.time(18, 0)],
      dtype=object)

In [21]:
df['hora_fin_VS_ra'].unique()

array([nan, datetime.time(0, 0), datetime.time(1, 0),
       datetime.time(23, 59), datetime.time(23, 0), datetime.time(0, 30),
       datetime.time(22, 0), datetime.time(2, 0), datetime.time(12, 0),
       datetime.time(23, 20), datetime.time(1, 30), datetime.time(2, 30),
       datetime.time(23, 30)], dtype=object)

In [22]:
import numpy as np

df['hora_ini_VS_es'] = df['hora_ini_VS_es'].replace(np.nan, "")
df['hora_fin_VS_es'] = df['hora_fin_VS_es'].replace(np.nan, "")

df['hora_ini_VS_ra'] = df['hora_ini_VS_ra'].replace(np.nan, "")
df['hora_fin_VS_ra'] = df['hora_fin_VS_ra'].replace(np.nan, "")

In [23]:
df = df.astype({"hora_ini_VS_es": str}, errors='raise') 
df = df.astype({"hora_fin_VS_es": str}, errors='raise') 
df = df.astype({"hora_ini_VS_ra": str}, errors='raise') 
df = df.astype({"hora_fin_VS_ra": str}, errors='raise')       

df.dtypes

_id                         int64
id_local                    int64
id_distrito_local           int64
desc_distrito_local        object
desc_barrio_local          object
clase_vial_edificio        object
num_edificio                int64
Cod_Postal                  int64
coordenada_x_local        float64
coordenada_y_local        float64
desc_situacion_local       object
Nombre                     object
id_periodo_terraza          int64
desc_periodo_terraza       object
id_situacion_terraza        int64
desc_situacion_terraza     object
Superficie_ES             float64
DESC_CLASE                 object
DESC_NOMBRE                object
num_terraza                 int64
cal_terraza                object
desc_ubicacion_terraza     object
hora_ini_LJ_es             object
hora_fin_LJ_es             object
hora_ini_LJ_ra             object
hora_fin_LJ_ra             object
hora_ini_VS_es             object
hora_fin_VS_es             object
hora_ini_VS_ra             object
hora_fin_VS_ra

In [24]:
df['hora_ini_VS_es'].unique()

array(['08:00:00', '10:00:00', '13:00:00', '02:30:00', '08:30:00',
       '12:00:00', '09:00:00', '01:30:00', '00:00:00', '10:24:00',
       '11:00:00'], dtype=object)

In [25]:
df['hora_fin_VS_es'].unique()

array(['01:30:00', '02:30:00', '00:00:00', '01:00:00', '00:30:00',
       '02:00:00', '22:00:00', '23:00:00', '21:00:00', '23:30:00',
       '12:00:00', '08:30:00', '20:30:00'], dtype=object)

In [26]:
df['hora_ini_VS_ra'].unique()

array(['', '10:00:00', '08:00:00', '09:00:00', '21:00:00', '02:30:00',
       '00:00:00', '11:00:00', '18:00:00'], dtype=object)

In [27]:
df['hora_fin_VS_ra'].unique()

array(['', '00:00:00', '01:00:00', '23:59:00', '23:00:00', '00:30:00',
       '22:00:00', '02:00:00', '12:00:00', '23:20:00', '01:30:00',
       '02:30:00', '23:30:00'], dtype=object)

In [28]:
import numpy as np

df['mesas_es'] = df['mesas_es'].fillna(0).replace(np.nan, 0).replace("" , 0)
df['mesas_aux_es'] = df['mesas_aux_es'].fillna(0).replace(np.nan, 0).replace("" , 0)

df['mesas_ra'] = df['mesas_ra'].fillna(0).replace(np.nan, 0).replace("" , 0)
df['mesas_aux_ra'] = df['mesas_aux_ra'].fillna(0).replace(np.nan, 0).replace("" , 0)

In [29]:
df['mesas_ra'].unique()

array([  0.,   9.,   8.,   6.,  21.,   3.,  10.,  12.,  30.,  16.,  15.,
        22.,  11.,   7.,  24.,  18.,  17.,   4.,  20.,  14.,   5.,  29.,
        26.,  28.,   2.,  13.,  25.,  19.,  23.,  27.,  38.,  57.,  37.,
        34.,  33.,   1.,  32.,  40.,  76.,  39.,  41.,  44.,  42., 112.])

In [30]:
df['mesas_aux_ra'].unique()

array([0., 1., 2.])

In [31]:
# Validar valores de la variable 'sillas_ra'
df['sillas_es'].unique()

array([ 10,  20,  27,  14,  24,  92,  35,   9,  16,  32,  12,  47,  13,
        36, 120, 112,  80,  44,  40,  56,  60,  18,  64,  88,  42,  28,
        96,  72,  68,  84,  30,  63,  61,  26,  21,  25,  48,  97,  31,
        76,  54, 152,  34,  38, 104, 107,   6,  43,  52,  11, 108, 100,
         4,  57,  23,  53,  33,  98,  66,  29,  15,  74,   8,  70,  99,
       105,  22,  50,  51, 124,  19,  45,  59,  17,  58,  69,  82, 136,
        46, 149, 116,  65,  90,   7,   0, 102, 115,  37, 156, 114, 110,
        39, 128, 113,  78,  55,  85,  94,   2,  71,  62, 125,  79,  67,
         5,  93,  81,  41,  86,  49, 118,  87, 160, 109,  77, 150,   3,
        75, 101,  95, 121, 106,  91,  73, 184, 117], dtype=int64)

In [32]:
# Validar columna 'sillas_ra'
df['sillas_ra'].unique()

array([' A', '  ', ' B', ' C', ' D', ' E', ' G', ' F', ' H',
       datetime.datetime(1900, 1, 1, 3, 13, 20), ' L'], dtype=object)

In [33]:
# Replazar valores con NULL
df['sillas_ra'] = df['sillas_ra'].fillna(0).replace(np.nan, 0).replace("" , 0)
df = df.astype({"mesas_ra": int}, errors='raise')  

In [34]:
# Replazando valores vacios y atipicos de la variable número de sillas 'sillas_ra'
df['sillas_ra'] = 0
df['sillas_ra'].unique()

array([0], dtype=int64)

In [35]:
df['mesas_es'].unique()

array([ 5, 10,  9,  4,  8,  6, 27, 14,  3, 12, 30, 21, 11, 16, 15, 22,  7,
       24, 18, 17, 25, 20, 38, 26, 28,  2, 13, 19, 23, 31, 29, 34, 57, 36,
        0, 37, 56, 55, 33,  1, 32, 35, 40, 39, 44, 46, 42], dtype=int64)

In [36]:
df['mesas_aux_es'].unique()

array([0, 1, 2, 4], dtype=int64)

In [37]:
df['mesas_ra'].unique()

array([  0,   9,   8,   6,  21,   3,  10,  12,  30,  16,  15,  22,  11,
         7,  24,  18,  17,   4,  20,  14,   5,  29,  26,  28,   2,  13,
        25,  19,  23,  27,  38,  57,  37,  34,  33,   1,  32,  40,  76,
        39,  41,  44,  42, 112])

In [38]:
df['mesas_aux_ra'].unique()

array([0., 1., 2.])

In [39]:
print(df.shape) 

(2999, 36)


In [40]:
df.tail(5)

_id   id_local  id_distrito_local  desc_distrito_local  \
2994  4640  270469031                 10               LATINA   
2995  4641  200000726                 20  SAN BLAS-CANILLEJAS   
2996  4642  270432183                 20  SAN BLAS-CANILLEJAS   
2997  4643  110002324                 11          CARABANCHEL   
2998  4647  270474279                  7             CHAMBERI   

     desc_barrio_local clase_vial_edificio  num_edificio  Cod_Postal  \
2994            ALUCHE               CALLE             7       28024   
2995             ROSAS             AVENIDA           131       28022   
2996             ROSAS             AVENIDA            67       28022   
2997      VISTA ALEGRE               CALLE             2       28025   
2998        RIOS ROSAS               CALLE            60       28003   

      coordenada_x_local  coordenada_y_local  ... hora_ini_VS_es  \
2994           435079.62          4471833.57  ...       10:00:00   
2995           448206.56          4475309.42  ...       10:00:00   
2996           448410.56          4476163.42  ...       08:00:00   
2997           437303.60          4471032.54  ...       10:00:00   
2998           440863.60          4477144.53  ...       08:00:00   

     hora_fin_VS_es  hora_ini_VS_ra hora_fin_VS_ra  mesas_aux_es mesas_aux_ra  \
2994       02:30:00        10:00:00       00:00:00             0          0.0   
2995       02:00:00                                            0          0.0   
2996       01:30:00        08:00:00       01:00:00             0          0.0   
2997       01:30:00                                            0          0.0   
2998       01:30:00        08:00:00       01:00:00             0          0.0   

      mesas_es mesas_ra sillas_es  sillas_ra  
2994         6        6        12          0  
2995         6        0        15          0  
2996        16        8        64          0  
2997        12        0        24          0  
2998         2        2         4          0  

[5 rows x 36 columns]

In [41]:
path ='C:/Users/anhel/OneDrive/Desktop/UNIR/Bases de datos para el Big Data/Actividad 3/visa01_grupal/'
file ='act-grupal-openDataLocalesMadrid-corregido.csv'
df.to_csv(path + file, index=0)